name: Deployment - PRD

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  AWS_REGION: "eu-central-1"
  TF_API_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
  TF_WORKING_DIRECTORY: "infra/terraform/prd"

jobs:
  infrastructure:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color

  code:
    name: "Deploy Code"
    needs: infrastructure
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNTID }}:role/GithubTrigger
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Code
        run: |
          set -e
          make deploy ENV=prd
          # Add health check command here
          echo "Deployment version: $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
